"""Emit AllObjects.xml for a generated workflow + ObjectLabel fixtures."""

from __future__ import annotations

from om_gen import DEFAULT_OBJECT_LABEL, OBJECT_LABEL_FIXTURES
from om_gen.emit_workflow import workflow_filename
from om_gen.ir import WorkflowIR

_LABEL_META = {
    OBJECT_LABEL_FIXTURES[0]: ('\\Root 0.0', 'Root 0.0'),
    OBJECT_LABEL_FIXTURES[1]: ('\\In Progress 0.0', 'In Progress 0.0'),
}


def emit_allobjects_xml(ir: WorkflowIR) -> str:
    h = ir.header
    label = h.object_label_name or DEFAULT_OBJECT_LABEL
    wf_file = workflow_filename(ir)
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Generated by om_gen — TRIRIGA Diagnostic Engine -->',
        '<OMObjects>',
        "    <OMObject Type='3'>",
        f'        <Module><![CDATA[{h.module}]]></Module>',
        f'        <BO><![CDATA[{h.bo}]]></BO>',
        f'        <Name><![CDATA[{h.name}]]></Name>',
        f'        <ObjectLabelName><![CDATA[{label}]]></ObjectLabelName>',
        f'        <File><![CDATA[{wf_file}]]></File>',
        '    </OMObject>',
    ]
    for fname in OBJECT_LABEL_FIXTURES:
        name, _ = _LABEL_META[fname]
        lines.extend([
            "    <OMObject Type='1011' IsIgnoreObjectLabelUpdate=\"1\">",
            '        <Module><![CDATA[triPlatformObjectLabelManager]]></Module>',
            '        <BO><![CDATA[triPlatformObjectLabelManager]]></BO>',
            f'        <Name><![CDATA[{name}]]></Name>',
            '        <ObjectLabelName><![CDATA[]]></ObjectLabelName>',
            f'        <File><![CDATA[{fname}]]></File>',
            '    </OMObject>',
        ])
    lines.append('</OMObjects>')
    return '\n'.join(lines)
